# Generated by Django 3.2 on 2021-05-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='billingAdress1',
            new_name='default_billingAdress1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='billingCity',
            new_name='default_billingCity',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='billingCountry',
            new_name='default_billingCountry',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='billingPostcode',
            new_name='default_billingPostcode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='default_phone',
        ),
    ]
