# Generated by Django 3.2 on 2021-05-21 21:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210521_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billingCountry',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='shippingCountry',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
